name: marshmallow
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  auto_route: ^7.4.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.1
  cloud_functions: ^4.3.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^2.2.1
  dartz: ^0.10.1
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_dynamic_links: ^5.3.3
  firebase_storage: ^11.2.4
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_google_places_sdk: ^0.3.2+9
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.3.1
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.0
  geolocator: ^8.0.0
  get: ^4.3.7
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  latlng: ^0.2.0
  map: ^1.4.1
  mask_text_input_formatter: ^2.4.0
  material_symbols_icons: ^4.2661.1
  permission_handler: ^10.3.0
  qr_flutter: ^4.1.0
  rive: ^0.11.4
  riverpod: ^2.1.1
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  pay: ^1.1.1
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  social_share: ^2.3.1
dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint: ^1.10.0

flutter_native_splash:
  color: "#FFEDFF"
  image: assets/images/logo.png

android_12:
  image: assets/images/logo.png
  color: "#FFEDFF"
  icon_background_color: "#FFEDFF"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
